### ISSUE TITLE
2024.8 has broken the integration

### ISSUE THREAD

**Issue by guidog66** [peaceduck/remootio#5]
Conflicting dependencies

**Comment by lbreggi** [comment]
same here

**Comment by Mewks** [comment]
Yup I've noticed this too. Would love if someone knows what needs to be updated! Thanks dev! <3 standing by for an update if you have time. @peaceduck

**Comment by Mewks** [comment]
> Conflicting dependencies



> same here

@guidog66 @lbreggi I have updated the code to get the integration working again. I'm no expert and the changes are very minimal mainly to the required versions. Everything is running fine for me.

I added my repo and just installed it over the top of peaceduck's. 

`https://github.com/Mewks/remootio`

**Comment by peaceduck** [comment]
Hi! Sorry for the problems. I am a few versions behind in my home assistant installation. Too much life has interfered with this development ;-) . I have tried to do a quick fix for this. Can someone try to reinstall and see if it works. Thanks!

**Comment by guidog66** [comment]
Thanks for the quick fix! All is well again for me

**Comment by peaceduck** [comment]
Cleaning up old issues. This integration seems to work now, and is updated in 2.0.2 with removed depreciated constants.
