### ISSUE TITLE
Unable to install package aioremootio @ git+https://github.com/peaceduck/aioremootio

### ISSUE THREAD

**Issue by adamk125** [peaceduck/remootio#6]
Hi @peaceduck,

Looks like this integration is now broken in the latest HA 2024.8 build with the below in the logs.

Any idea how to fix it, love the integration and we use it daily :(

![image](https://github.com/user-attachments/assets/8a0afc4a-07b4-4e46-a9f2-32dd9dbfdca7)

**Comment by TerminalAddict** [comment]
Upgrade to 2024.8 breaks remootio integration.

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 8:52:20 AM (3 occurrences)
Last logged: 8:52:47 AM

Unable to install package aioremootio @ git+https://github.com/peaceduck/aioremootio: ERROR: Cannot install aioremootio==1.0.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

I'm guessing something about
https://github.com/peaceduck/aioremootio/blob/master/requirements.txt

**Comment by peaceduck** [comment]
Hi! Sorry for the problems. I have tried to make a quick fix for this. Can you try to reinstall the version and see if it works? I am behind on my home assistant installation, so I can not test it right now...

**Comment by adamk125** [comment]
> Hi! Sorry for the problems. I have tried to make a quick fix for this. Can you try to reinstall the version and see if it works? I am behind on my home assistant installation, so I can not test it right now...

Many thanks.

Hey @TerminalAddict - any chance you can test this for us? I downgraded back to 2024.7.4 so we could use the garage hah!

**Comment by TerminalAddict** [comment]
Yip, all working 
![Screenshot_20240808_201850_Home Assistant](https://github.com/user-attachments/assets/7582d66c-4511-47f7-8176-34dbbc1f0559)

**Comment by SnapperThatch** [comment]
Just tested, all working here. Thanks

**Comment by TerminalAddict** [comment]
groan .. updated to 2024.8.1 . .2 of my devices work, 1 doesn't
```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 7:12:23 PM (1 occurrences)
Last logged: 7:12:23 PM

Error setting up entry Remootio Device (Host: 103.123.164.91, S/N: a0dd6c12fe70ijhnniws) for remootio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remootio/__init__.py", line 38, in async_setup_entry
    remootio_client: RemootioClient = await create_client(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remootio/utils.py", line 91, in create_client
    await _check_api_version(result)
  File "/config/custom_components/remootio/utils.py", line 34, in _check_api_version
    if api_version < EXPECTED_MINIMUM_API_VERSION:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by TerminalAddict** [comment]
oh .. interesting .. I restarted the remootio device, and HA picked it up .. must been in a glitchy state .. phew .. ha not broken again. :)

**Comment by peaceduck** [comment]
Cleaning up old tickets. This seems to work :-)
